name: tfsec
on: [pull_request]

jobs:
  ubuntu:
    name: tfsec / ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terrafrom
        working-directory: .
        run: |
          terraform init
    
      - name: Run tfsec with reviewdog output on the PR
        uses: reviewdog/action-tfsec@revamp-n-move-to-composite
        with:
          github_token: ${{ secrets.github_token }}
          working_directory: . # Change working directory
          reviewdog_log_level: info # Get more output from reviewdog
          reviewdog_reporter: github-pr-review # Change reviewdog reporter
          reviewdog_filter_mode: nofilter # Check all files, not just the diff
          reviewdog_fail_on_error: true # Fail action if errors are found
          reviewdog_flags: -tee # Add debug flag to reviewdog
          tfsec_flags: "" # Optional
