name: tfsec
on: [pull_request]

jobs:
  ubuntu:
    name: tfsec / ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terrafrom
        working-directory: .
        run: |
          terraform init

      - name: Run tfsec with review comment on PR
        uses: vlaaaaaaad/action-tfsec@debug
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working_directory: .
          reporter: github-pr-review
          fail_on_error: true
          filter_mode: nofilter
          level: info
          flags: --no-color
